"""Basic shelf-stable foods for in-kind donation — curated subset (min shelf life 180 days)."""

FOOD: list[dict] = [
    {"category": "FOOD", "display_name": "Arroz blanco", "default_unit": "kg", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Arroz integral", "default_unit": "kg", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Frijol negro", "default_unit": "kg", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Frijol pinto", "default_unit": "kg", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Frijol en lata", "default_unit": "latas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Lenteja", "default_unit": "kg", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Garbanzo", "default_unit": "kg", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Haba seca", "default_unit": "kg", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Atún en lata", "default_unit": "latas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Sardina en lata", "default_unit": "latas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Aceite vegetal", "default_unit": "botellas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Leche en polvo", "default_unit": "bolsas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Leche evaporada", "default_unit": "latas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Harina de maíz", "default_unit": "kg", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Harina de trigo", "default_unit": "kg", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Azúcar", "default_unit": "kg", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Sal", "default_unit": "kg", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Avena", "default_unit": "kg", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Pasta", "default_unit": "paquetes", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Fideos", "default_unit": "paquetes", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Sopa instantánea", "default_unit": "sobres", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Galletas", "default_unit": "paquetes", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Galletas saladas", "default_unit": "paquetes", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Cereal", "default_unit": "cajas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Café", "default_unit": "bolsas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Puré de tomate", "default_unit": "latas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Salsa de tomate", "default_unit": "botellas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Miel", "default_unit": "botellas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Chocolate en polvo", "default_unit": "bolsas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Nuez / fruto seco", "default_unit": "bolsas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Barra de granola", "default_unit": "piezas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Maíz en lata", "default_unit": "latas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Chícharo en lata", "default_unit": "latas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Durazno en lata", "default_unit": "latas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Mantequilla de maní", "default_unit": "botellas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Mermelada", "default_unit": "botellas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Café soluble", "default_unit": "bolsas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Fórmula infantil", "default_unit": "latas", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Harina de arroz", "default_unit": "kg", "min_shelf_life_days": 180},
    {"category": "FOOD", "display_name": "Frijol blanco", "default_unit": "kg", "min_shelf_life_days": 180},
]
