import { notFound } from "next/navigation"
import { headers } from "next/headers"
import type { Metadata } from "next"
import { StatusTimeline } from "@/components/StatusTimeline"
import { DEFAULT_OG_IMAGE } from "@/lib/seo"

const API_URL = process.env.API_URL ?? "http://localhost:8000"

type Loc = "es" | "en"

// This page is scanned from a physical QR (not URL-locale, not SEO-enumerable).
// The inventory DATA is Spanish (admin/catalog); only the UI LABELS are localized
// via the scanner's browser language, so an international volunteer in the field
// reads "Product / Batch / Expiry" instead of "Producto / Lote / Caducidad".
async function detectLocale(): Promise<Loc> {
  const h = await headers()
  const al = (h.get("accept-language") ?? "").toLowerCase()
  return al.startsWith("en") ? "en" : "es"
}

interface QrLabels {
  categories: Record<string, string>
  statuses: Record<string, string>
  product: string
  category: string
  inn: string
  strength: string
  form: string
  batchExpiry: string
  batch: string
  expiry: string
  quantityWeight: string
  quantity: string
  weight: string
  origin: string
  center: string
  campaign: string
  sealed: string
  summary: string
  boxesRow: string
  totalWeight: string
  closed: string
  contents: (n: number) => string
  history: string
  pallet: string
  notFound: string
  footer: string
  boxesWord: string
  dateLocale: string
}

const LABELS: Record<Loc, QrLabels> = {
  es: {
    categories: { MEDICINE: "Medicamento", MEDICAL_SUPPLY: "Insumo médico", FOOD: "Alimento", WATER: "Agua", HYGIENE: "Higiene", TOOL: "Herramienta", RESCUE_GEAR: "Equipo de rescate", OTHER: "Otro" },
    statuses: { DRAFT: "Borrador", SEALED: "Sellada", SHIPPED: "Despachada", REJECTED: "Rechazada", OPEN: "Abierta", CLOSED: "Cerrada" },
    product: "Producto", category: "Categoría", inn: "INN", strength: "Concentración", form: "Forma farmacéutica",
    batchExpiry: "Lote y caducidad", batch: "Lote", expiry: "Caducidad",
    quantityWeight: "Cantidad y peso", quantity: "Cantidad", weight: "Peso",
    origin: "Origen", center: "Centro", campaign: "Campaña", sealed: "Sellada",
    summary: "Resumen", boxesRow: "Cajas", totalWeight: "Peso total", closed: "Cerrada",
    contents: (n) => `Contenido (${n} cajas)`,
    history: "Historial", pallet: "Tarima", notFound: "Ficha no encontrada",
    footer: "Generado por Araguaney · datos al momento del escaneo",
    boxesWord: "cajas", dateLocale: "es-MX",
  },
  en: {
    categories: { MEDICINE: "Medicine", MEDICAL_SUPPLY: "Medical supply", FOOD: "Food", WATER: "Water", HYGIENE: "Hygiene", TOOL: "Tool", RESCUE_GEAR: "Rescue gear", OTHER: "Other" },
    statuses: { DRAFT: "Draft", SEALED: "Sealed", SHIPPED: "Shipped", REJECTED: "Rejected", OPEN: "Open", CLOSED: "Closed" },
    product: "Product", category: "Category", inn: "INN", strength: "Strength", form: "Dosage form",
    batchExpiry: "Batch & expiry", batch: "Batch", expiry: "Expiry",
    quantityWeight: "Quantity & weight", quantity: "Quantity", weight: "Weight",
    origin: "Origin", center: "Center", campaign: "Campaign", sealed: "Sealed",
    summary: "Summary", boxesRow: "Boxes", totalWeight: "Total weight", closed: "Closed",
    contents: (n) => `Contents (${n} boxes)`,
    history: "History", pallet: "Pallet", notFound: "Ficha not found",
    footer: "Generated by Araguaney · data at scan time",
    boxesWord: "boxes", dateLocale: "en-US",
  },
}

const STATUS_COLORS: Record<string, string> = {
  DRAFT: "bg-zinc-100 text-zinc-700",
  SEALED: "bg-green-100 text-green-700",
  SHIPPED: "bg-blue-100 text-blue-700",
  REJECTED: "bg-red-100 text-red-700",
  OPEN: "bg-amber-100 text-amber-700",
  CLOSED: "bg-green-100 text-green-700",
}

function fmt(kg: number | null | undefined): string {
  if (kg == null) return "—"
  if (kg >= 1000) return `${(kg / 1000).toFixed(2)} t`
  return `${Number(kg).toFixed(1)} kg`
}

interface QrEvent {
  from_status: string | null
  to_status: string
  note: string | null
  ts: string
}

interface BoxFicha {
  kind: "box"
  code: string
  status: string
  display_name: string
  category: string
  inn_name: string | null
  strength: string | null
  form: string | null
  batch: string | null
  expiry_date: string | null
  quantity: number
  unit: string
  weight_kg: number | null
  center_name: string
  campaign_name: string | null
  sealed_at: string | null
  created_at: string
  events: QrEvent[]
}

interface PalletBoxRow {
  display_name: string
  category: string
  quantity: number
  unit: string
  weight_kg: number | null
}

interface PalletFicha {
  kind: "pallet"
  code: string
  status: string
  center_name: string
  box_count: number
  total_weight_kg: number | null
  closed_at: string | null
  created_at: string
  boxes: PalletBoxRow[]
  events: QrEvent[]
}

type Ficha = BoxFicha | PalletFicha

async function fetchFicha(code: string): Promise<Ficha | null> {
  try {
    const res = await fetch(`${API_URL}/v1/public/qr/${encodeURIComponent(code)}`, {
      next: { revalidate: 60, tags: [`qr-${code}`] },
    })
    if (!res.ok) return null
    return res.json()
  } catch {
    return null
  }
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ code: string }>
}): Promise<Metadata> {
  const { code } = await params
  const [ficha, locale] = await Promise.all([fetchFicha(code), detectLocale()])
  const L = LABELS[locale]

  if (!ficha) {
    return { title: L.notFound, robots: { index: false, follow: false } }
  }

  const title =
    ficha.kind === "box" ? `${ficha.display_name} — QR` : `${L.pallet} ${ficha.code} — QR`
  const description =
    ficha.kind === "box"
      ? `${ficha.code} · ${ficha.center_name} · ${ficha.quantity} ${ficha.unit}`
      : `${ficha.code} · ${ficha.center_name} · ${ficha.box_count} ${L.boxesWord}`

  return {
    title,
    description,
    alternates: { canonical: `/qr/${ficha.code}` },
    openGraph: { title, description, images: [DEFAULT_OG_IMAGE] },
    twitter: { card: "summary_large_image", title, description, images: [DEFAULT_OG_IMAGE] },
  }
}

export default async function QrFichaPage({
  params,
}: {
  params: Promise<{ code: string }>
}) {
  const { code } = await params
  const [ficha, locale] = await Promise.all([fetchFicha(code), detectLocale()])

  if (!ficha) notFound()
  const L = LABELS[locale]

  const statusColor = STATUS_COLORS[ficha.status] ?? "bg-zinc-100 text-zinc-700"
  const statusLabel = L.statuses[ficha.status] ?? ficha.status

  return (
    <div className="min-h-screen bg-zinc-50">
      <div className="mx-auto max-w-lg px-4 py-8">
        {/* Header */}
        <div className="mb-6">
          <p className="text-xs text-zinc-500 font-mono mb-1">{ficha.code}</p>
          <div className="flex items-center gap-3">
            <h1 className="text-2xl font-bold text-zinc-900 leading-tight">
              {ficha.kind === "box" ? ficha.display_name : `${L.pallet} ${ficha.code}`}
            </h1>
            <span className={`shrink-0 rounded-full px-3 py-1 text-sm font-medium ${statusColor}`}>
              {statusLabel}
            </span>
          </div>
        </div>

        {ficha.kind === "box" && <BoxSection ficha={ficha} L={L} />}
        {ficha.kind === "pallet" && <PalletSection ficha={ficha} L={L} />}

        {/* Timeline */}
        {ficha.events.length > 0 && (
          <section className="mt-8">
            <h2 className="text-sm font-semibold text-zinc-500 uppercase tracking-wide mb-4">
              {L.history}
            </h2>
            <StatusTimeline events={ficha.events} />
          </section>
        )}

        <p className="mt-10 text-center text-xs text-zinc-300">{L.footer}</p>
      </div>
    </div>
  )
}

function Row({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex justify-between py-2.5 border-b border-zinc-100 last:border-0">
      <span className="text-sm text-zinc-500">{label}</span>
      <span className="text-sm font-medium text-zinc-900 text-right max-w-[60%]">{value ?? "—"}</span>
    </div>
  )
}

function BoxSection({ ficha, L }: { ficha: BoxFicha; L: QrLabels }) {
  return (
    <>
      {/* Product details */}
      <section className="rounded-xl border border-zinc-200 bg-white divide-y divide-zinc-100 mb-4">
        <div className="px-4 py-3">
          <p className="text-xs font-semibold text-zinc-500 uppercase tracking-wide">{L.product}</p>
        </div>
        <div className="px-4">
          <Row label={L.category} value={L.categories[ficha.category] ?? ficha.category} />
          {ficha.inn_name && <Row label={L.inn} value={ficha.inn_name} />}
          {ficha.strength && <Row label={L.strength} value={ficha.strength} />}
          {ficha.form && <Row label={L.form} value={ficha.form} />}
        </div>
      </section>

      {/* Lot / expiry */}
      <section className="rounded-xl border border-zinc-200 bg-white divide-y divide-zinc-100 mb-4">
        <div className="px-4 py-3">
          <p className="text-xs font-semibold text-zinc-500 uppercase tracking-wide">{L.batchExpiry}</p>
        </div>
        <div className="px-4">
          <Row label={L.batch} value={ficha.batch} />
          <Row
            label={L.expiry}
            value={
              ficha.expiry_date
                ? new Date(ficha.expiry_date).toLocaleDateString(L.dateLocale, { year: "numeric", month: "long", day: "numeric" })
                : null
            }
          />
        </div>
      </section>

      {/* Quantity & weight */}
      <section className="rounded-xl border border-zinc-200 bg-white divide-y divide-zinc-100 mb-4">
        <div className="px-4 py-3">
          <p className="text-xs font-semibold text-zinc-500 uppercase tracking-wide">{L.quantityWeight}</p>
        </div>
        <div className="px-4">
          <Row label={L.quantity} value={`${ficha.quantity} ${ficha.unit}`} />
          <Row label={L.weight} value={fmt(ficha.weight_kg)} />
        </div>
      </section>

      {/* Context */}
      <section className="rounded-xl border border-zinc-200 bg-white divide-y divide-zinc-100">
        <div className="px-4 py-3">
          <p className="text-xs font-semibold text-zinc-500 uppercase tracking-wide">{L.origin}</p>
        </div>
        <div className="px-4">
          <Row label={L.center} value={ficha.center_name} />
          {ficha.campaign_name && <Row label={L.campaign} value={ficha.campaign_name} />}
          <Row
            label={L.sealed}
            value={
              ficha.sealed_at
                ? new Date(ficha.sealed_at).toLocaleString(L.dateLocale, { day: "numeric", month: "short", year: "numeric" })
                : null
            }
          />
        </div>
      </section>
    </>
  )
}

function PalletSection({ ficha, L }: { ficha: PalletFicha; L: QrLabels }) {
  return (
    <>
      {/* Summary */}
      <section className="rounded-xl border border-zinc-200 bg-white divide-y divide-zinc-100 mb-4">
        <div className="px-4 py-3">
          <p className="text-xs font-semibold text-zinc-500 uppercase tracking-wide">{L.summary}</p>
        </div>
        <div className="px-4">
          <Row label={L.center} value={ficha.center_name} />
          <Row label={L.boxesRow} value={String(ficha.box_count)} />
          <Row label={L.totalWeight} value={fmt(ficha.total_weight_kg)} />
          <Row
            label={L.closed}
            value={
              ficha.closed_at
                ? new Date(ficha.closed_at).toLocaleString(L.dateLocale, { day: "numeric", month: "short", year: "numeric" })
                : null
            }
          />
        </div>
      </section>

      {/* Box list */}
      {ficha.boxes.length > 0 && (
        <section className="rounded-xl border border-zinc-200 bg-white overflow-hidden">
          <div className="px-4 py-3 border-b border-zinc-100">
            <p className="text-xs font-semibold text-zinc-500 uppercase tracking-wide">
              {L.contents(ficha.boxes.length)}
            </p>
          </div>
          <ul className="divide-y divide-zinc-100">
            {ficha.boxes.map((b, i) => (
              <li key={i} className="flex items-center justify-between px-4 py-3 gap-2">
                <div className="min-w-0">
                  <p className="text-sm font-medium text-zinc-900 truncate">{b.display_name}</p>
                  <p className="text-xs text-zinc-500">{L.categories[b.category] ?? b.category}</p>
                </div>
                <div className="text-right shrink-0">
                  <p className="text-sm font-medium text-zinc-900">{b.quantity} {b.unit}</p>
                  <p className="text-xs text-zinc-500">{fmt(b.weight_kg)}</p>
                </div>
              </li>
            ))}
          </ul>
        </section>
      )}
    </>
  )
}
