import {
  type Locale,
  type RouteKey,
  LOCALES,
  DEFAULT_LOCALE,
  localizedPath,
} from "@/lib/routes"

// Canonical host is www: production 308-redirects the apex (araguaney.lat) to
// www.araguaney.lat, and the Google Search Console property is verified on www.
// Keep this in sync with NEXT_PUBLIC_SITE_URL in Vercel and the redirect at the
// edge — every canonical/sitemap/robots URL derives from here.
export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.araguaney.lat"
).replace(/\/$/, "")

// Single source of truth for the brand entity's `sameAs` links — the
// authoritative external profiles Google/AI use to resolve the entity in the
// knowledge graph. Empty until the accounts exist: add each official URL here
// (LinkedIn, GitHub, X, Instagram, Crunchbase) and, once created, the Wikidata
// entity URL (Fase 17 task 6). They flow into the Organization schema
// automatically — only rendered when non-empty. See Fase 17 task 5.
export const BRAND_SAME_AS: readonly string[] = []

// Public founder attribution for the Organization `founder` (E-E-A-T signal).
export const BRAND_FOUNDING_YEAR = "2026"
export const BRAND_FOUNDER_NAME = "Antony E Delgado Casanova"

export function absoluteUrl(path: string): string {
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`
}

// Shared default share image. Next.js metadata does NOT deep-merge nested
// objects (openGraph, twitter) between layout.tsx and a page's own metadata —
// a page defining `openGraph: { title, description }` completely REPLACES
// the layout's `openGraph`, silently dropping `images`. Every page that
// defines its own openGraph/twitter metadata must re-include this image
// (or its own) explicitly; it will not fall back to the layout's.
export const DEFAULT_OG_IMAGE =
  "https://res.cloudinary.com/dtvdqlxtd/image/upload/w_1200,h_630,c_pad,b_white,f_png/v1782786243/araguaney_logo_ol8lm1"

// Branded per-page share card generated by app/og/route.tsx. Pass a page title
// (and optional eyebrow) to get its own Open Graph image instead of the logo.
export function ogImageUrl(title: string, eyebrow?: string): string {
  const params = new URLSearchParams({ title })
  if (eyebrow) params.set("eyebrow", eyebrow)
  return absoluteUrl(`/og?${params.toString()}`)
}

// Canonical + hreflang alternates for a migrated route, for `metadata.alternates`.
// Emits one `hreflang` per supported locale plus `x-default` (the default locale).
// Paths are relative; Next resolves them against metadataBase. Generic over
// LOCALES so a new language is included automatically.
export function alternates(key: RouteKey, locale: Locale) {
  const languages: Record<string, string> = {}
  for (const l of LOCALES) {
    languages[l] = localizedPath(key, l)
  }
  languages["x-default"] = localizedPath(key, DEFAULT_LOCALE)
  return {
    canonical: localizedPath(key, locale),
    languages,
  }
}
